before:
  hooks:
    - go mod tidy
builds:
  - id: knocker
    main: ./cmd/knocker
    binary: knocker
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - id: packages
    package_name: knocker
    vendor: FarisZR
    homepage: https://github.com/FarisZR/knocker-cli
    maintainer: FarisZR <35614734+FarisZR@users.noreply.github.com>
    description: A reliable, cross-platform service that keeps your external IP address whitelisted.
    license: Apache-2.0
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/knocker/LICENSE
    scripts:
      postinstall: scripts/postinstall.sh
      preremove: scripts/preremove.sh
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'