name: Build Release artifacts

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    name: Publish release artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean --skip=announce
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
